version: '3.1'
services:
  db:
    image: postgres
    restart: always
    container_name: employees-postrgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: employees
      POSTGRES_USER: admin